apiVersion: apps/v1
kind: Deployment
metadata:
  name: AuditBenchamrkApi-deployment
  labels:
    app: AuditBenchamrkApiService
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AuditBenchamrkApi;  
  template:
    metadata:
      labels:
        app: AuditBenchamrkApi
    spec:
      containers:
      - name: AuditBenchamrkApi
        image: dntacr1.azurecr.io/auditbenchmarkapi:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: webapisvcsecret
---
apiVersion: v1
kind: Service
metadata:
  name: AuditBenchamrkApiService
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: AuditBenchamrkApi